/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

  sidebar: [
    // 'intro',
    {
      type: 'category',
      label: 'Team',
      items: [
        {
          type: 'autogenerated',
          dirName: 'common'
        }
      ],
    },
    {
      type: 'category',
      label: 'Backend',
      items: [
        {
          type: 'autogenerated',
          dirName: 'backend'
        }
      ],
    },
    {
      type: 'category',
      label: 'Frontend',
      items: [
        {
          type: 'autogenerated',
          dirName: 'frontend'
        }
      ],
    },
    {
      type: 'category',
      label: '회의록',
      items: [
        {
          type: 'autogenerated',
          dirName: 'meetingnotes'
        }
      ],
    },
  ],
};

export default sidebars;
